// File generated by Antigravity to support Firebase compilation.
// To override these values with live configurations, run: flutterfire configure --project=fixora-7714e
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-web',
    appId: '1:1234567890:web:mock12345',
    messagingSenderId: '1234567890',
    projectId: 'fixora-7714e',
    authDomain: 'fixora-7714e.firebaseapp.com',
    storageBucket: 'fixora-7714e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-android',
    appId: '1:1234567890:android:mock12345',
    messagingSenderId: '1234567890',
    projectId: 'fixora-7714e',
    storageBucket: 'fixora-7714e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-ios',
    appId: '1:1234567890:ios:mock12345',
    messagingSenderId: '1234567890',
    projectId: 'fixora-7714e',
    storageBucket: 'fixora-7714e.appspot.com',
    iosBundleId: 'com.example.fixora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-macos',
    appId: '1:1234567890:ios:mock12345',
    messagingSenderId: '1234567890',
    projectId: 'fixora-7714e',
    storageBucket: 'fixora-7714e.appspot.com',
    iosBundleId: 'com.example.fixora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-mock-key-windows',
    appId: '1:1234567890:web:mock12345',
    messagingSenderId: '1234567890',
    projectId: 'fixora-7714e',
    authDomain: 'fixora-7714e.firebaseapp.com',
    storageBucket: 'fixora-7714e.appspot.com',
  );
}
